### ISSUE TITLE
Install with non-standard libpostal location

### ISSUE THREAD

**Issue by kylebarron** [openvenues/node-postal#20]
I don't have sudo access to the server I'm working on, so I installed libpostal into `~/local/lib`. My `LD_LIBRARY_PATH` is set correctly, and the libpostal tests passed so I believe it installed correctly. But `npm install node-postal` fails because it can't find `libpostal/libpostal.h`. Is it possible to install node-postal using the local library path?

**Comment by albarrentine** [comment]
Hi @kylebarron, should be able to either edit https://github.com/openvenues/node-postal/blob/master/binding.gyp and add `-L ~/local/lib` (may need to be an absolute path), or just install without sudo using the default prefix /usr/local/lib.

**Comment by kylebarron** [comment]
Thanks! I was able to change `/usr/local/lib` to `$HOME/local/lib` and `/usr/local/include` to `$HOME/local/include`.

**Comment by kylebarron** [comment]
@albarrentine It seems to correctly install when I change the paths in `binding.gyp`, but then tests don't work. Do you have an idea of how to fix this?

```
> npm install node-postal
... 
../src/expand.cc:1:33: fatal error: libpostal/libpostal.h: No such file or directory
 #include <libpostal/libpostal.h>
...

> cd node_modules/node-postal
> sed -i "s@/usr/local/lib@$HOME/local/lib@g" binding.gyp
> sed -i "s@/usr/local/include@$HOME/local/include@g" binding.gyp
> npm install
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> node-postal@1.0.0 install /disk/homedirs/barronk/tmp/node_modules/node-postal
> (node-gyp rebuild) || (exit 0)

make: Entering directory `/disk/homedirs/barronk/tmp/node_modules/node-postal/build'
  CXX(target) Release/obj.target/expand/src/expand.o
  SOLINK_MODULE(target) Release/obj.target/expand.node
  COPY Release/expand.node
  CXX(target) Release/obj.target/parser/src/parser.o
  SOLINK_MODULE(target) Release/obj.target/parser.node
  COPY Release/parser.node
make: Leaving directory `/disk/homedirs/barronk/tmp/node_modules/node-postal/build'
npm notice created a lockfile as package-lock.json. You should commit this file.
added 22 packages in 5.374s
```

But the test fails:
```
> npm test

> node-postal@1.0.0 test /disk/homedirs/barronk/tmp/node_modules/node-postal
> mocha ./test

ERR   Error loading transliteration module, dir=(null)
   at libpostal_setup_datadir (libpostal.c:266) errno: No such file or directory
/disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/bindings/bindings.js:88
        throw e
        ^

Error: Could not load libpostal
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at bindings (/disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/disk/homedirs/barronk/tmp/node_modules/node-postal/index.js:3:32)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/disk/homedirs/barronk/tmp/node_modules/node-postal/test/index.test.js:1:76)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at /disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/mocha/lib/mocha.js:220:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/mocha/lib/mocha.js:217:14)
    at Mocha.run (/disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/mocha/lib/mocha.js:469:10)
    at Object.<anonymous> (/disk/homedirs/barronk/tmp/node_modules/node-postal/node_modules/mocha/bin/_mocha:404:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! Test failed.  See above for more details.
```

**Comment by albarrentine** [comment]
Hm, if I'm remembering this right, you might need to set `LD_LIBRARY_PATH` as well at test/usage time. Check out our [Travis build](https://github.com/openvenues/node-postal/blob/master/.travis.yml) which installs libpostal in the working directory.

**Comment by kylebarron** [comment]
My `LD_LIBRARY_PATH` is set to
```
> echo $LD_LIBRARY_PATH 
:/homes/nber/barronk/local/lib:/homes/nber/barronk/local/anaconda3/lib
```
and the libpostal libraries are in the former of those two:
```
> ll /homes/nber/barronk/local/lib/ | grep postal
-rw-r--r-- 1 barronk barronk   13M Mar 20 00:07 libpostal.a
-rwxr-xr-x 1 barronk barronk   998 Mar 20 00:07 libpostal.la*
lrwxrwxrwx 1 barronk barronk    18 Mar 20 00:07 libpostal.so -> libpostal.so.1.0.0*
lrwxrwxrwx 1 barronk barronk    18 Mar 20 00:07 libpostal.so.1 -> libpostal.so.1.0.0*
-rwxr-xr-x 1 barronk barronk   11M Mar 20 00:07 libpostal.so.1.0.0*
```

I'll check out the travis build

**Comment by kylebarron** [comment]
Thanks, the Travis build instructions helped. I needed to fix the `CXXFLAGS` and `LDFLAGS`
