### ISSUE TITLE
node-postal does not build on nodejs versions >10.x (see pull request #25)

### ISSUE THREAD

**Issue by BryanWall** [openvenues/node-postal#27]
I tried installing node-postal on the latest LTS version of node (v12.18.3) and get the following errors (it builds and works fine on node v10.x). I've tried every solution that comes up on a Google search for this error and still get the same result. This is on Macos Catalina v10.15.6

```
19 warnings and 2 errors generated.
make: *** [Release/obj.target/expand/src/expand.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxxxx/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/xxxxx/.nvm/versions/node/v12.18.3/bin/node" "/Users/xxxxx/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxxx/dev/libtest/node_modules/node-postal
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN libtest@1.0.0 No description
npm WARN libtest@1.0.0 No repository field.
```

**Comment by BryanWall** [comment]
Complete terminal history

```
xxxxx@MacBook-Pro libtest % nvm use 12                                                    
Now using node v12.18.3 (npm v6.14.6)
xxxxx@MacBook-Pro libtest % npm rebuild                                                   

> node-postal@1.0.0 install /Users/xxxxx/dev/libtest/node_modules/node-postal
> (node-gyp rebuild) || (exit 0)

  CXX(target) Release/obj.target/expand/src/expand.o
../src/expand.cc:34:48: error: no matching member function for call to 'ToObject'
        v8::Local<v8::Object> props = info[1]->ToObject();
                                      ~~~~~~~~~^~~~~~~~
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:2672:44: note: candidate function not viable: requires single argument 'context', but no
      arguments were provided
  V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                           ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:2686:31: note: candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
                Local<Object> ToObject(Isolate* isolate) const);
                              ^
../src/expand.cc:39:52: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
            v8::Local<v8::Value> key = prop_names->Get(i);
                                                   ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3557:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:53:68: warning: 'Get' is deprecated: Use maybe version [-Wdeprecated-declarations]
                            Nan::Utf8String lang_utf8(langs_value->Get(j));
                                                                   ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3557:3: note: 'Get' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version", Local<Value> Get(uint32_t index));
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:119:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
        ret->Set(i, e);
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3507:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:138:122: error: too few arguments to function call, single argument 'context' was not specified
    exports->Set(Nan::New("expand_address").ToLocalChecked(), Nan::New<v8::FunctionTemplate>(ExpandAddress)->GetFunction());
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:6126:3: note: 'GetFunction' declared here
  V8_WARN_UNUSED_RESULT MaybeLocal<Function> GetFunction(
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:368:31: note: expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../src/expand.cc:140:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_NONE").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_NONE));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:141:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_ANY").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_ANY));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:142:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_NAME").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_NAME));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:143:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_HOUSE_NUMBER").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_HOUSE_NUMBER));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:144:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_STREET").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_STREET));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:145:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_UNIT").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_UNIT));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:146:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_LEVEL").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_LEVEL));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:147:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_STAIRCASE").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_STAIRCASE));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:148:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_ENTRANCE").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_ENTRANCE));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:150:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_CATEGORY").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_CATEGORY));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:151:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_NEAR").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_NEAR));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:153:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_TOPONYM").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_TOPONYM));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:154:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_POSTAL_CODE").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_POSTAL_CODE));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:155:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_PO_BOX").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_PO_BOX));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:156:14: warning: 'Set' is deprecated: Use maybe version [-Wdeprecated-declarations]
    exports->Set(Nan::New("ADDRESS_ALL").ToLocalChecked(), Nan::New(LIBPOSTAL_ADDRESS_ALL));
             ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8.h:3498:3: note: 'Set' has been explicitly marked deprecated here
  V8_DEPRECATED("Use maybe version",
  ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/v8config.h:328:29: note: expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
../src/expand.cc:162:11: warning: 'AtExit' is deprecated: Use the three-argument variant of AtExit() or AddEnvironmentCleanupHook()
      [-Wdeprecated-declarations]
    node::AtExit(cleanup);
          ^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/node.h:700:1: note: 'AtExit' has been explicitly marked deprecated here
NODE_DEPRECATED(
^
/Users/xxxxx/Library/Caches/node-gyp/12.18.3/include/node/node.h:101:20: note: expanded from macro 'NODE_DEPRECATED'
    __attribute__((deprecated(message))) declarator
                   ^
19 warnings and 2 errors generated.
make: *** [Release/obj.target/expand/src/expand.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/xxxxx/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/Users/xxxxx/.nvm/versions/node/v12.18.3/bin/node" "/Users/xxxxx/.nvm/versions/node/v12.18.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxxxx/dev/libtest/node_modules/node-postal
gyp ERR! node -v v12.18.3
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
node-postal@1.0.0 /Users/xxxxx/dev/libtest/node_modules/node-postal
bindings@1.5.0 /Users/xxxxx/dev/libtest/node_modules/bindings
file-uri-to-path@1.0.0 /Users/xxxxx/dev/libtest/node_modules/file-uri-to-path
nan@2.14.1 /Users/xxxxx/dev/libtest/node_modules/nan
xxxxx@MacBook-Pro libtest % 
```

**Comment by BryanWall** [comment]
I just noticed that @kembuco has already submitted a pull request #25 to fix this. I tested it today and it works on both node 12.x and 14.x.

**Comment by orangejulius** [comment]
Hey @albarrentine,
Would you be interested in adding me and/or @missinglink as maintainers of `node-postal`? We use libpostal through Node.js quite heavily with Pelias to this day, and we'd be happy of taking on the task of reviewing and merging PRs to keep `node-postal` up to date with the latest changes in Node.js. Let us know or shoot me an email :)

**Comment by orangejulius** [comment]
Fixed in https://github.com/openvenues/node-postal/pull/25
